<a href="https://colab.research.google.com/github/flaviohnm/projeto_bancodedados/blob/main/aeronave.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

#Instalação do módulos

In [ ]:
#pip install pandera

#Bloco de Extração

In [ ]:
import pandas as pd
import pandera as pa

In [ ]:
df = pd.read_csv("/content/drive/MyDrive/CENIPA/aeronave.csv",sep=";")

## O comando "head" exibe a quantidade de linhas contida no parentesis.

In [ ]:
df.head(10)

,codigo_ocorrencia2,aeronave_matricula,aeronave_operador_categoria,aeronave_tipo_veiculo,aeronave_fabricante,aeronave_modelo,aeronave_tipo_icao,aeronave_motor_tipo,aeronave_motor_quantidade,aeronave_pmd,...,aeronave_pais_fabricante,aeronave_pais_registro,aeronave_registro_categoria,aeronave_registro_segmento,aeronave_voo_origem,aeronave_voo_destino,aeronave_fase_operacao,aeronave_tipo_operacao,aeronave_nivel_dano,aeronave_fatalidades_total
0,45331,PRTKB,***,AVIÃO,AEROSPATIALE AND ALENIA,ATR-42-500,AT45,TURBOÉLICE,BIMOTOR,18600,...,BRASIL,BRASIL,AVIÃO,REGULAR,FORA DE AERODROMO,FORA DE AERODROMO,DESCIDA,REGULAR,NENHUM,0
1,45332,PTUDD,***,AVIÃO,NEIVA INDUSTRIA AERONAUTICA,EMB-201A,IPAN,PISTÃO,MONOMOTOR,1800,...,BRASIL,BRASIL,AVIÃO,ESPECIALIZADA,FORA DE AERODROMO,FORA DE AERODROMO,DECOLAGEM,AGRÍCOLA,SUBSTANCIAL,0
2,45333,PTGOO,***,AVIÃO,NEIVA INDUSTRIA AERONAUTICA,EMB-201,IPAN,PISTÃO,MONOMOTOR,1800,...,BRASIL,BRASIL,AVIÃO,ESPECIALIZADA,FORA DE AERODROMO,FORA DE AERODROMO,ESPECIALIZADA,AGRÍCOLA,SUBSTANCIAL,0
3,45334,PRMHX,REGULAR,AVIÃO,AIRBUS INDUSTRIE,A320-214,A320,JATO,BIMOTOR,77000,...,BRASIL,BRASIL,AVIÃO,REGULAR,FORA DE AERODROMO,FORA DE AERODROMO,CORRIDA APÓS POUSO,REGULAR,LEVE,0
4,45390,PTUEW,***,AVIÃO,NEIVA INDUSTRIA AERONAUTICA,EMB-201A,IPAN,PISTÃO,MONOMOTOR,1800,...,BRASIL,BRASIL,AVIÃO,AGRÍCOLA,FORA DE AERODROMO,FORA DE AERODROMO,ESPECIALIZADA,AGRÍCOLA,SUBSTANCIAL,0
5,45391,PTLUP,PARTICULAR,AVIÃO,CESSNA AIRCRAFT,P210N,P210,PISTÃO,MONOMOTOR,1812,...,BRASIL,BRASIL,AVIÃO,PARTICULAR,FORA DE AERODROMO,FORA DE AERODROMO,CRUZEIRO,PRIVADA,SUBSTANCIAL,0
6,45392,PPMOF,***,HELICÓPTERO,ROBINSON HELICOPTER,R44,R44,TURBOEIXO,MONOMOTOR,1088,...,BRASIL,BRASIL,HELICÓPTERO,PARTICULAR,PRESIDENTE JUSCELINO KUBITSCHEK,SANTA GENOVEVA/GOIÂNIA,DECOLAGEM,PRIVADA,SUBSTANCIAL,0
7,45393,PTDHU,***,AVIÃO,PIPER AIRCRAFT,PA-30,PA30,PISTÃO,BIMOTOR,1633,...,BRASIL,BRASIL,AVIÃO,INSTRUÇÃO,FRANCISCO DE ASSIS,SANTOS DUMONT,POUSO,INSTRUÇÃO,SUBSTANCIAL,0
8,45396,PRJMR,***,AVIÃO,PIPER AIRCRAFT,PA-34-220T,PA34,PISTÃO,BIMOTOR,2155,...,BRASIL,BRASIL,AVIÃO,PARTICULAR,JOÃO CORREA DA ROCHA,CARAJÁS,SUBIDA,PRIVADA,LEVE,0
9,45397,PTYLS,***,HELICÓPTERO,EUROCOPTER FRANCE,AS 350 B2,AS50,TURBOEIXO,MONOMOTOR,2250,...,BRASIL,BRASIL,HELICÓPTERO,MÚLTIPLA,SANTOS DUMONT,ANGRA DOS REIS,CRUZEIRO,NÃO REGULAR,SUBSTANCIAL,0

'BRASIL'

Exibir os tipos de dados dos objetos

In [ ]:
df.dtypes

codigo_ocorrencia                          int64
codigo_ocorrencia1                         int64
codigo_ocorrencia2                         int64
codigo_ocorrencia3                         int64
codigo_ocorrencia4                         int64
ocorrencia_classificacao                  object
ocorrencia_latitude                       object
ocorrencia_longitude                      object
ocorrencia_cidade                         object
ocorrencia_uf                             object
ocorrencia_pais                           object
ocorrencia_aerodromo                      object
ocorrencia_dia                    datetime64[ns]
ocorrencia_hora                           object
investigacao_aeronave_liberada            object
investigacao_status                       object
divulgacao_relatorio_numero               object
divulgacao_relatorio_publicado            object
divulgacao_dia_publicacao                 object
total_recomendacoes                        int64
total_aeronaves_envolvidas                 int64
ocorrencia_saida_pista                    object
dtype: object

Até esse trecho foi realizado o carregamento de dados com a conversão das colunas que contém datas para o tipo de dado "date" com o método "parse".

In [ ]:
df.replace(['***','**','####','###!','****','*****','NULL'], pd.NA, inplace=True)

In [ ]:
schema = pa.DataFrameSchema(
    columns = {
        "codigo_ocorrencia":pa.Column(pa.Int),
        "codigo_ocorrencia1":pa.Column(pa.Int),
        "codigo_ocorrencia2":pa.Column(pa.Int),
        "codigo_ocorrencia3":pa.Column(pa.Int),
        "codigo_ocorrencia4":pa.Column(pa.Int),
        "ocorrencia_classificacao":pa.Column(pa.String),
        "ocorrencia_latitude": pa.Column((pa.String),nullable=True),
        "ocorrencia_longitude":pa.Column((pa.String),nullable=True),
        "ocorrencia_cidade":pa.Column(pa.String),
        "ocorrencia_uf":pa.Column(pa.String, pa.Check.str_length(2,2),nullable=True),
        "ocorrencia_pais":pa.Column(pa.String),
        "ocorrencia_aerodromo":pa.Column((pa.String),nullable=True),
        "investigacao_aeronave_liberada":pa.Column((pa.String),nullable=True),
        "investigacao_status":pa.Column((pa.String),nullable=True),
        "divulgacao_relatorio_numero":pa.Column((pa.String),nullable=True),
        "divulgacao_relatorio_publicado":pa.Column((pa.String),nullable=True),
        "divulgacao_dia_publicacao":pa.Column((pa.String),nullable=True),
        "ocorrencia_dia":pa.Column(pa.DateTime),
        "ocorrencia_hora":pa.Column(pa.String, pa.Check.str_matches(r'^([0-1]?[0-9]|[2][0-3]):([0-5][0-9])(:[0-5][0-9])?$'),nullable=True),
        "total_recomendacoes":pa.Column(pa.Int),
        "total_aeronaves_envolvidas":pa.Column(pa.Int),
        "ocorrencia_saida_pista":pa.Column(pa.String)
    }
)

In [ ]:
df.isnull().sum()

codigo_ocorrencia                    0
codigo_ocorrencia1                   0
codigo_ocorrencia2                   0
codigo_ocorrencia3                   0
codigo_ocorrencia4                   0
ocorrencia_classificacao             0
ocorrencia_latitude               1493
ocorrencia_longitude              1494
ocorrencia_cidade                    0
ocorrencia_uf                        2
ocorrencia_pais                      0
ocorrencia_aerodromo              1905
ocorrencia_dia                       0
ocorrencia_hora                      1
investigacao_aeronave_liberada    1778
investigacao_status                257
divulgacao_relatorio_numero       3298
divulgacao_relatorio_publicado       0
divulgacao_dia_publicacao         3816
total_recomendacoes                  0
total_aeronaves_envolvidas           0
ocorrencia_saida_pista               0
dtype: int64

##Validação do Schema

In [ ]:
schema.validate(df)

,codigo_ocorrencia,codigo_ocorrencia1,codigo_ocorrencia2,codigo_ocorrencia3,codigo_ocorrencia4,ocorrencia_classificacao,ocorrencia_latitude,ocorrencia_longitude,ocorrencia_cidade,ocorrencia_uf,...,ocorrencia_dia,ocorrencia_hora,investigacao_aeronave_liberada,investigacao_status,divulgacao_relatorio_numero,divulgacao_relatorio_publicado,divulgacao_dia_publicacao,total_recomendacoes,total_aeronaves_envolvidas,ocorrencia_saida_pista
0,52242,52242,52242,52242,52242,INCIDENTE,NaN,NaN,PORTO ALEGRE,RS,...,2012-01-05,20:27:00,<NA>,FINALIZADA,<NA>,NÃO,NaN,0,1,NÃO
1,45331,45331,45331,45331,45331,ACIDENTE,-23.4355555556,-46.4730555556,GUARULHOS,SP,...,2012-01-06,13:44:00,SIM,FINALIZADA,A-582/CENIPA/2014,SIM,2016-09-01,3,1,NÃO
2,45333,45333,45333,45333,45333,ACIDENTE,<NA>,<NA>,VIAMÃO,RS,...,2012-01-06,13:00:00,NaN,FINALIZADA,A-070/CENIPA/2013,SIM,2013-11-27,0,1,NÃO
3,45401,45401,45401,45401,45401,ACIDENTE,<NA>,<NA>,SÃO SEBASTIÃO,SP,...,2012-01-06,17:00:00,<NA>,NaN,NaN,NÃO,NaN,0,1,NÃO
4,45407,45407,45407,45407,45407,ACIDENTE,<NA>,<NA>,SÃO SEPÉ,RS,...,2012-01-06,16:30:00,SIM,FINALIZADA,A-071/CENIPA/2013,SIM,2013-11-27,0,1,NÃO
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5162,80458,80458,80458,80458,80458,ACIDENTE,-17.999194,-51.642861,JATAÍ,GO,...,2021-12-30,20:30:00,SIM,ATIVA,A DEFINIR,NÃO,NaN,0,1,NÃO
5163,80452,80452,80452,80452,80452,ACIDENTE,-22.585556,-50.753889,MARACAÍ,SP,...,2021-12-31,09:30:00,SIM,ATIVA,A DEFINIR,NÃO,NaN,0,1,NÃO
5164,80457,80457,80457,80457,80457,INCIDENTE GRAVE,-29.695833,-51.081667,NOVO HAMBURGO,RS,...,2021-12-31,11:59:00,SIM,FINALIZADA,<NA>,NÃO,NaN,0,1,NÃO
5165,80460,80460,80460,80460,80460,INCIDENTE,-25.403333,-49.233611,CURITIBA,PR,...,2021-12-31,15:12:00,SIM,FINALIZADA,<NA>,NÃO,NaN,0,1,NÃO
5166,80467,80467,80467,80467,80467,INCIDENTE,-9.3675,-40.56361111111,PETROLINA,PE,...,2021-12-31,20:30:00,SIM,FINALIZADA,<NA>,NÃO,NaN,0,1,NÃO

##Checando se o valor da coluna "codigo ocorrência" são únicos.

In [ ]:
df.codigo_ocorrencia.is_unique

True

Definindo "codigo da ocorrência" como indice

In [ ]:
df.set_index('codigo_ocorrencia', inplace=True)

Consultar quantos NA tem no dataframe

In [ ]:
df.isna().sum()

codigo_ocorrencia1                   0
codigo_ocorrencia2                   0
codigo_ocorrencia3                   0
codigo_ocorrencia4                   0
ocorrencia_classificacao             0
ocorrencia_latitude               1493
ocorrencia_longitude              1494
ocorrencia_cidade                    0
ocorrencia_uf                        2
ocorrencia_pais                      0
ocorrencia_aerodromo              1905
ocorrencia_dia                       0
ocorrencia_hora                      1
investigacao_aeronave_liberada    1778
investigacao_status                257
divulgacao_relatorio_numero       3298
divulgacao_relatorio_publicado       0
divulgacao_dia_publicacao         3816
total_recomendacoes                  0
total_aeronaves_envolvidas           0
ocorrencia_saida_pista               0
dtype: int64

In [ ]:
df.isnull().sum()

codigo_ocorrencia1                   0
codigo_ocorrencia2                   0
codigo_ocorrencia3                   0
codigo_ocorrencia4                   0
ocorrencia_classificacao             0
ocorrencia_latitude               1493
ocorrencia_longitude              1494
ocorrencia_cidade                    0
ocorrencia_uf                        2
ocorrencia_pais                      0
ocorrencia_aerodromo              1905
ocorrencia_dia                       0
ocorrencia_hora                      1
investigacao_aeronave_liberada    1778
investigacao_status                257
divulgacao_relatorio_numero       3298
divulgacao_relatorio_publicado       0
divulgacao_dia_publicacao         3816
total_recomendacoes                  0
total_aeronaves_envolvidas           0
ocorrencia_saida_pista               0
dtype: int64