<a href="https://colab.research.google.com/github/flaviohnm/projeto_bancodedados/blob/main/ocorrencias_nova.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Instalação do módulos

In [226]:
! pip install pandera
! pip install pymongo
! pip install dnspython

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: pandera in /usr/local/lib/python3.7/dist-packages (0.9.0)
Requirement already satisfied: pandas>=1.0 in /usr/local/lib/python3.7/dist-packages (from pandera) (1.3.5)
Requirement already satisfied: numpy>=1.9.0 in /usr/local/lib/python3.7/dist-packages (from pandera) (1.21.6)
Requirement already satisfied: typing-inspect>=0.6.0 in /usr/local/lib/python3.7/dist-packages (from pandera) (0.7.1)
Requirement already satisfied: wrapt in /usr/local/lib/python3.7/dist-packages (from pandera) (1.14.1)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /usr/local/lib/python3.7/dist-packages (from pandera) (4.1.1)
Requirement already satisfied: pyarrow in /usr/local/lib/python3.7/dist-packages (from pandera) (6.0.1)
Requirement already satisfied: pydantic in /usr/local/lib/python3.7/dist-packages (from pandera) (1.8.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.7/dist-packages (from pandera) (21.3)
Requirement already satisfied: pyparsing!=3.0.5,>=2.0.2 in /usr/local/lib/python3.7/dist-packages (from packaging>=20.0->pandera) (3.0.9)
Requirement already satisfied: python-dateutil>=2.7.3 in /usr/local/lib/python3.7/dist-packages (from pandas>=1.0->pandera) (2.8.2)
Requirement already satisfied: pytz>=2017.3 in /usr/local/lib/python3.7/dist-packages (from pandas>=1.0->pandera) (2022.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.7/dist-packages (from python-dateutil>=2.7.3->pandas>=1.0->pandera) (1.15.0)
Requirement already satisfied: mypy-extensions>=0.3.0 in /usr/local/lib/python3.7/dist-packages (from typing-inspect>=0.6.0->pandera) (0.4.3)
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: pymongo in /usr/local/lib/python3.7/dist-packages (4.1.1)
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: dnspython in /usr/local/lib/python3.7/dist-packages (2.2.1)

#Bloco de Extração

In [227]:
import pandas as pd
import pandera as pa
import pymongo
from pymongo import MongoClient as mc

In [228]:
df = pd.read_csv("/content/drive/MyDrive/projeto_bancodedados/ocorrencia.csv",sep=";",parse_dates=['ocorrencia_dia'],dayfirst=True)

## O comando "head" exibe a quantidade de linhas contida no parentesis.

In [229]:
df.head(10)

,codigo_ocorrencia,codigo_ocorrencia1,codigo_ocorrencia2,codigo_ocorrencia3,codigo_ocorrencia4,ocorrencia_classificacao,ocorrencia_latitude,ocorrencia_longitude,ocorrencia_cidade,ocorrencia_uf,...,ocorrencia_dia,ocorrencia_hora,investigacao_aeronave_liberada,investigacao_status,divulgacao_relatorio_numero,divulgacao_relatorio_publicado,divulgacao_dia_publicacao,total_recomendacoes,total_aeronaves_envolvidas,ocorrencia_saida_pista
0,52242,52242,52242,52242,52242,INCIDENTE,NaN,NaN,PORTO ALEGRE,RS,...,2012-01-05,20:27:00,***,FINALIZADA,***,NÃO,NaN,0,1,NÃO
1,45331,45331,45331,45331,45331,ACIDENTE,-23.4355555556,-46.4730555556,GUARULHOS,SP,...,2012-01-06,13:44:00,SIM,FINALIZADA,A-582/CENIPA/2014,SIM,2016-09-01,3,1,NÃO
2,45333,45333,45333,45333,45333,ACIDENTE,***,***,VIAMÃO,RS,...,2012-01-06,13:00:00,NaN,FINALIZADA,A-070/CENIPA/2013,SIM,2013-11-27,0,1,NÃO
3,45401,45401,45401,45401,45401,ACIDENTE,***,***,SÃO SEBASTIÃO,SP,...,2012-01-06,17:00:00,***,NaN,NaN,NÃO,NaN,0,1,NÃO
4,45407,45407,45407,45407,45407,ACIDENTE,***,***,SÃO SEPÉ,RS,...,2012-01-06,16:30:00,SIM,FINALIZADA,A-071/CENIPA/2013,SIM,2013-11-27,0,1,NÃO
5,52243,52243,52243,52243,52243,INCIDENTE,NaN,NaN,UBATUBA,SP,...,2012-01-06,14:30:00,***,FINALIZADA,***,NÃO,NaN,0,1,NÃO
6,50713,50713,50713,50713,50713,INCIDENTE GRAVE,***,***,CAMPINAS,SP,...,2012-01-07,18:15:00,SIM,FINALIZADA,IG-184/CENIPA/2013,SIM,2014-01-08,0,1,NÃO
7,45334,45334,45334,45334,45334,INCIDENTE,NaN,NaN,BELÉM,PA,...,2012-01-08,19:12:00,***,FINALIZADA,***,NÃO,NaN,0,1,NÃO
8,45391,45391,45391,45391,45391,ACIDENTE,-19.9133333333,-48.2930555556,CONCEIÇÃO DAS ALAGOAS,MG,...,2012-01-08,16:00:00,***,FINALIZADA,A DEFINIR,NÃO,NaN,0,1,NÃO
9,52244,52244,52244,52244,52244,INCIDENTE,***,***,UBERLÂNDIA,MG,...,2012-01-08,22:13:00,***,FINALIZADA,***,NÃO,NaN,0,1,NÃO

Exibir os tipos de dados dos objetos

In [230]:
df.dtypes

codigo_ocorrencia                          int64
codigo_ocorrencia1                         int64
codigo_ocorrencia2                         int64
codigo_ocorrencia3                         int64
codigo_ocorrencia4                         int64
ocorrencia_classificacao                  object
ocorrencia_latitude                       object
ocorrencia_longitude                      object
ocorrencia_cidade                         object
ocorrencia_uf                             object
ocorrencia_pais                           object
ocorrencia_aerodromo                      object
ocorrencia_dia                    datetime64[ns]
ocorrencia_hora                           object
investigacao_aeronave_liberada            object
investigacao_status                       object
divulgacao_relatorio_numero               object
divulgacao_relatorio_publicado            object
divulgacao_dia_publicacao                 object
total_recomendacoes                        int64
total_aeronaves_envolvidas                 int64
ocorrencia_saida_pista                    object
dtype: object

Até esse trecho foi realizado o carregamento de dados com a conversão das colunas que contém datas para o tipo de dado "date" com o método "parse".

In [231]:
df.isnull().sum()

codigo_ocorrencia                    0
codigo_ocorrencia1                   0
codigo_ocorrencia2                   0
codigo_ocorrencia3                   0
codigo_ocorrencia4                   0
ocorrencia_classificacao             0
ocorrencia_latitude                975
ocorrencia_longitude               975
ocorrencia_cidade                    0
ocorrencia_uf                        0
ocorrencia_pais                      0
ocorrencia_aerodromo                 0
ocorrencia_dia                       0
ocorrencia_hora                      1
investigacao_aeronave_liberada     166
investigacao_status                257
divulgacao_relatorio_numero        384
divulgacao_relatorio_publicado       0
divulgacao_dia_publicacao         3816
total_recomendacoes                  0
total_aeronaves_envolvidas           0
ocorrencia_saida_pista               0
dtype: int64

##Validação do Schema

##Checando se o valor da coluna "codigo ocorrência" são únicos.

In [232]:
df.codigo_ocorrencia.is_unique

True

Definindo "codigo da ocorrência" como indice

In [233]:
df.set_index('codigo_ocorrencia', inplace=True)

Consultar quantos NA tem no dataframe

In [234]:
df.isna().sum()

codigo_ocorrencia1                   0
codigo_ocorrencia2                   0
codigo_ocorrencia3                   0
codigo_ocorrencia4                   0
ocorrencia_classificacao             0
ocorrencia_latitude                975
ocorrencia_longitude               975
ocorrencia_cidade                    0
ocorrencia_uf                        0
ocorrencia_pais                      0
ocorrencia_aerodromo                 0
ocorrencia_dia                       0
ocorrencia_hora                      1
investigacao_aeronave_liberada     166
investigacao_status                257
divulgacao_relatorio_numero        384
divulgacao_relatorio_publicado       0
divulgacao_dia_publicacao         3816
total_recomendacoes                  0
total_aeronaves_envolvidas           0
ocorrencia_saida_pista               0
dtype: int64

In [235]:
df.isnull().sum()

codigo_ocorrencia1                   0
codigo_ocorrencia2                   0
codigo_ocorrencia3                   0
codigo_ocorrencia4                   0
ocorrencia_classificacao             0
ocorrencia_latitude                975
ocorrencia_longitude               975
ocorrencia_cidade                    0
ocorrencia_uf                        0
ocorrencia_pais                      0
ocorrencia_aerodromo                 0
ocorrencia_dia                       0
ocorrencia_hora                      1
investigacao_aeronave_liberada     166
investigacao_status                257
divulgacao_relatorio_numero        384
divulgacao_relatorio_publicado       0
divulgacao_dia_publicacao         3816
total_recomendacoes                  0
total_aeronaves_envolvidas           0
ocorrencia_saida_pista               0
dtype: int64

###Consultas

In [249]:
#consulta1 | Ocorrências com Latitude e Longitude preenchida
df.query(ocorrencia_latitude != NaN)

NameError: ignored

In [237]:
ocorrencias = df

In [238]:
ocorrencias.head(10)

,codigo_ocorrencia1,codigo_ocorrencia2,codigo_ocorrencia3,codigo_ocorrencia4,ocorrencia_classificacao,ocorrencia_latitude,ocorrencia_longitude,ocorrencia_cidade,ocorrencia_uf,ocorrencia_pais,...,ocorrencia_dia,ocorrencia_hora,investigacao_aeronave_liberada,investigacao_status,divulgacao_relatorio_numero,divulgacao_relatorio_publicado,divulgacao_dia_publicacao,total_recomendacoes,total_aeronaves_envolvidas,ocorrencia_saida_pista
codigo_ocorrencia,,,,,,,,,,,,,,,,,,,,,
52242,52242,52242,52242,52242,INCIDENTE,NaN,NaN,PORTO ALEGRE,RS,BRASIL,...,2012-01-05,20:27:00,***,FINALIZADA,***,NÃO,NaN,0,1,NÃO
45331,45331,45331,45331,45331,ACIDENTE,-23.4355555556,-46.4730555556,GUARULHOS,SP,BRASIL,...,2012-01-06,13:44:00,SIM,FINALIZADA,A-582/CENIPA/2014,SIM,2016-09-01,3,1,NÃO
45333,45333,45333,45333,45333,ACIDENTE,***,***,VIAMÃO,RS,BRASIL,...,2012-01-06,13:00:00,NaN,FINALIZADA,A-070/CENIPA/2013,SIM,2013-11-27,0,1,NÃO
45401,45401,45401,45401,45401,ACIDENTE,***,***,SÃO SEBASTIÃO,SP,BRASIL,...,2012-01-06,17:00:00,***,NaN,NaN,NÃO,NaN,0,1,NÃO
45407,45407,45407,45407,45407,ACIDENTE,***,***,SÃO SEPÉ,RS,BRASIL,...,2012-01-06,16:30:00,SIM,FINALIZADA,A-071/CENIPA/2013,SIM,2013-11-27,0,1,NÃO
52243,52243,52243,52243,52243,INCIDENTE,NaN,NaN,UBATUBA,SP,BRASIL,...,2012-01-06,14:30:00,***,FINALIZADA,***,NÃO,NaN,0,1,NÃO
50713,50713,50713,50713,50713,INCIDENTE GRAVE,***,***,CAMPINAS,SP,BRASIL,...,2012-01-07,18:15:00,SIM,FINALIZADA,IG-184/CENIPA/2013,SIM,2014-01-08,0,1,NÃO
45334,45334,45334,45334,45334,INCIDENTE,NaN,NaN,BELÉM,PA,BRASIL,...,2012-01-08,19:12:00,***,FINALIZADA,***,NÃO,NaN,0,1,NÃO
45391,45391,45391,45391,45391,ACIDENTE,-19.9133333333,-48.2930555556,CONCEIÇÃO DAS ALAGOAS,MG,BRASIL,...,2012-01-08,16:00:00,***,FINALIZADA,A DEFINIR,NÃO,NaN,0,1,NÃO
52244,52244,52244,52244,52244,INCIDENTE,***,***,UBERLÂNDIA,MG,BRASIL,...,2012-01-08,22:13:00,***,FINALIZADA,***,NÃO,NaN,0,1,NÃO

###Dados da conexão com o MongoDB no Atlas (AWS)

In [239]:
uri = "mongodb+srv://mongo_user:MongoUser1234@cluster0.6qfwp.mongodb.net/starwars?retryWrites=true&w=majority" #url de conexão
client = mc(uri)

In [240]:
#teste de conexão com o banco
client.stats

Database(MongoClient(host=['cluster0-shard-00-02.6qfwp.mongodb.net:27017', 'cluster0-shard-00-01.6qfwp.mongodb.net:27017', 'cluster0-shard-00-00.6qfwp.mongodb.net:27017'], document_class=dict, tz_aware=False, connect=True, retrywrites=True, w='majority', authsource='admin', replicaset='atlas-r075ws-shard-0', tls=True), 'stats')

In [241]:
db = client.list_database_names()
print(db)

['mestrado', 'projetobd', 'starwars', 'admin', 'local']

In [242]:
data = ocorrencias
ocorrencias.head(10)

,codigo_ocorrencia1,codigo_ocorrencia2,codigo_ocorrencia3,codigo_ocorrencia4,ocorrencia_classificacao,ocorrencia_latitude,ocorrencia_longitude,ocorrencia_cidade,ocorrencia_uf,ocorrencia_pais,...,ocorrencia_dia,ocorrencia_hora,investigacao_aeronave_liberada,investigacao_status,divulgacao_relatorio_numero,divulgacao_relatorio_publicado,divulgacao_dia_publicacao,total_recomendacoes,total_aeronaves_envolvidas,ocorrencia_saida_pista
codigo_ocorrencia,,,,,,,,,,,,,,,,,,,,,
52242,52242,52242,52242,52242,INCIDENTE,NaN,NaN,PORTO ALEGRE,RS,BRASIL,...,2012-01-05,20:27:00,***,FINALIZADA,***,NÃO,NaN,0,1,NÃO
45331,45331,45331,45331,45331,ACIDENTE,-23.4355555556,-46.4730555556,GUARULHOS,SP,BRASIL,...,2012-01-06,13:44:00,SIM,FINALIZADA,A-582/CENIPA/2014,SIM,2016-09-01,3,1,NÃO
45333,45333,45333,45333,45333,ACIDENTE,***,***,VIAMÃO,RS,BRASIL,...,2012-01-06,13:00:00,NaN,FINALIZADA,A-070/CENIPA/2013,SIM,2013-11-27,0,1,NÃO
45401,45401,45401,45401,45401,ACIDENTE,***,***,SÃO SEBASTIÃO,SP,BRASIL,...,2012-01-06,17:00:00,***,NaN,NaN,NÃO,NaN,0,1,NÃO
45407,45407,45407,45407,45407,ACIDENTE,***,***,SÃO SEPÉ,RS,BRASIL,...,2012-01-06,16:30:00,SIM,FINALIZADA,A-071/CENIPA/2013,SIM,2013-11-27,0,1,NÃO
52243,52243,52243,52243,52243,INCIDENTE,NaN,NaN,UBATUBA,SP,BRASIL,...,2012-01-06,14:30:00,***,FINALIZADA,***,NÃO,NaN,0,1,NÃO
50713,50713,50713,50713,50713,INCIDENTE GRAVE,***,***,CAMPINAS,SP,BRASIL,...,2012-01-07,18:15:00,SIM,FINALIZADA,IG-184/CENIPA/2013,SIM,2014-01-08,0,1,NÃO
45334,45334,45334,45334,45334,INCIDENTE,NaN,NaN,BELÉM,PA,BRASIL,...,2012-01-08,19:12:00,***,FINALIZADA,***,NÃO,NaN,0,1,NÃO
45391,45391,45391,45391,45391,ACIDENTE,-19.9133333333,-48.2930555556,CONCEIÇÃO DAS ALAGOAS,MG,BRASIL,...,2012-01-08,16:00:00,***,FINALIZADA,A DEFINIR,NÃO,NaN,0,1,NÃO
52244,52244,52244,52244,52244,INCIDENTE,***,***,UBERLÂNDIA,MG,BRASIL,...,2012-01-08,22:13:00,***,FINALIZADA,***,NÃO,NaN,0,1,NÃO

In [243]:
db = client['projetobd']
collection = db['ocorrencias']

In [244]:
#carregando o dataframe ocorrencias no mongodb
ocorrencias_dict = ocorrencias.to_dict("records")
collection.insert_many(ocorrencias_dict)

In [245]:
print(ocorrencias_dict)

IOPub data rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_data_rate_limit`.

Current values:
NotebookApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
NotebookApp.rate_limit_window=3.0 (secs)

In [246]:
#listando um registro já cadastrado no mongo
busca = collection.find_one()
print(busca)

{'_id': ObjectId('62bb5d56c9f245150b5c45dc'), 'codigo_ocorrencia1': 52242, 'codigo_ocorrencia2': 52242, 'codigo_ocorrencia3': 52242, 'codigo_ocorrencia4': 52242, 'ocorrencia_classificacao': 'INCIDENTE', 'ocorrencia_latitude': nan, 'ocorrencia_longitude': nan, 'ocorrencia_cidade': 'PORTO ALEGRE', 'ocorrencia_uf': 'RS', 'ocorrencia_pais': 'BRASIL', 'ocorrencia_aerodromo': 'SBPA', 'ocorrencia_dia': datetime.datetime(2012, 1, 5, 0, 0), 'ocorrencia_hora': '20:27:00', 'investigacao_aeronave_liberada': '***', 'investigacao_status': 'FINALIZADA', 'divulgacao_relatorio_numero': '***', 'divulgacao_relatorio_publicado': 'NÃO', 'divulgacao_dia_publicacao': nan, 'total_recomendacoes': 0, 'total_aeronaves_envolvidas': 1, 'ocorrencia_saida_pista': 'NÃO'}

In [247]:
#estrutura para excluir a coleção
db = client['projetobd']
collection = db['ocorrencias']
#collection.drop()